//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSlackCleaner.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSlackCleaner.Resources.Localization.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string btnAbort {
            get {
                return ResourceManager.GetString("btnAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete found messages.
        /// </summary>
        public static string btnDeleteMessages {
            get {
                return ResourceManager.GetString("btnDeleteMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string btnOk {
            get {
                return ResourceManager.GetString("btnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private channels.
        /// </summary>
        public static string gboxPrivateChannels {
            get {
                return ResourceManager.GetString("gboxPrivateChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private messages.
        /// </summary>
        public static string gboxPrivateMessages {
            get {
                return ResourceManager.GetString("gboxPrivateMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public channels.
        /// </summary>
        public static string gboxPublicChannels {
            get {
                return ResourceManager.GetString("gboxPublicChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the token required to run the application or.
        /// </summary>
        public static string lblEnterTokenOrGenerateIt {
            get {
                return ResourceManager.GetString("lblEnterTokenOrGenerateIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generate it.
        /// </summary>
        public static string lblGenerateToken {
            get {
                return ResourceManager.GetString("lblGenerateToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search messages older than:.
        /// </summary>
        public static string lblSearchMessagesOlderThan {
            get {
                return ResourceManager.GetString("lblSearchMessagesOlderThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token:.
        /// </summary>
        public static string lblToken {
            get {
                return ResourceManager.GetString("lblToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following address could not be launched in the browser:
        ///{0}.
        /// </summary>
        public static string msgCannotOpenWebUrl {
            get {
                return ResourceManager.GetString("msgCannotOpenWebUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token cannot be empty..
        /// </summary>
        public static string msgEmptyToken {
            get {
                return ResourceManager.GetString("msgEmptyToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token..
        /// </summary>
        public static string msgInvalidToken {
            get {
                return ResourceManager.GetString("msgInvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSlackCleaner.
        /// </summary>
        public static string TitleApplicationName {
            get {
                return ResourceManager.GetString("TitleApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string TitleInformation {
            get {
                return ResourceManager.GetString("TitleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string TitleToken {
            get {
                return ResourceManager.GetString("TitleToken", resourceCulture);
            }
        }
    }
}
